### ISSUE TITLE
Loading states

### ISSUE THREAD

**Issue by dianezhou96** [dianezhou96/lululedger#12]
Check for places where different content shows up before the desired content.

- CartSelector

**Comment by dianezhou96** [comment]
Skeleton done for Account, Order, and CartSelector.

**Comment by 0xAl3xH** [comment]
increase size of loading spinner and center vertically to be more consistent with other loading screens

**Comment by 0xAl3xH** [comment]
increase spinner size for cart selector and disable it from dropping down while cart is dirty because the add cart row has some weird sizing issue while loading:
<img width="266" alt="Screen Shot 2023-06-18 at 12 27 33" src="https://github.com/dianezhou96/lululedger/assets/20210402/ce38533e-5a66-4bac-816d-9f470b62efd9">
disabled while lo
<img width="260" alt="Screen Shot 2023-06-18 at 12 24 11" src="https://github.com/dianezhou96/lululedger/assets/20210402/47e0bb3a-567b-451f-899e-bf1e18bb0b73">
ading so users don't see this:

**Comment by 0xAl3xH** [comment]
might have introduced a bug where adding to cart causes the loading screen to show up? is cart dirty set to true after adding to cart? @dianezhou96

**Comment by dianezhou96** [comment]
Yes cart dirty is set to true after adding to cart. Can optimize this if #17 yields a need for it
